# Generated by Django 5.1.7 on 2025-03-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointData',
            fields=[
                ('gid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('direction', models.IntegerField()),
                ('velocity', models.IntegerField()),
                ('dt', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('vehicle_id', models.BigIntegerField()),
                ('vehicle_class', models.CharField(max_length=2)),
                ('zone_id', models.BigIntegerField()),
                ('trip_id', models.BigIntegerField()),
                ('fid', models.BigIntegerField()),
                ('ts_insert', models.DateTimeField()),
            ],
            options={
                'db_table': '"data"."data"',
                'indexes': [models.Index(fields=['vehicle_id'], name='data_vehicle_9e5042_idx'), models.Index(fields=['trip_id'], name='data_trip_id_c9271a_idx'), models.Index(fields=['zone_id'], name='data_zone_id_3b6caa_idx')],
            },
        ),
    ]
